# Generated by Django 3.0.3 on 2020-04-20 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comorbidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Numele conditiei medicale')),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Sursa de informare')),
                ('parsed_content', models.TextField(verbose_name='Continutul parsat')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Numele spitalului')),
            ],
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.PositiveIntegerField(unique=True, verbose_name='Numarul cazului')),
                ('hospital_admission_date', models.DateField(verbose_name='Data internarii')),
                ('positive_result_date', models.DateField(verbose_name='Data rezultatului pozitiv')),
                ('death_date', models.DateField(verbose_name='Data decesului')),
                ('parsed_text', models.TextField(verbose_name='Textul interpretat')),
                ('validated', models.BooleanField(verbose_name='Deces verificat manual')),
                ('comorbidities', models.ManyToManyField(to='api_core.Comorbidity', verbose_name='Comorbiditati (conditii medicale existente)')),
                ('final_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finally_admitted_deaths', to='api_core.Hospital', verbose_name='Spitalul decesului')),
                ('initial_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initially_admitted_deaths', to='api_core.Hospital', verbose_name='Spitalul de internare initial')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_core.DataSource', verbose_name='Sursa de date')),
            ],
        ),
    ]
