# Generated by Django 3.0.3 on 2020-04-22 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comorbidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Numele conditiei medicale')),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='Sursa de informare')),
                ('parsed_content', models.TextField(verbose_name='Continutul parsat')),
                ('title', models.TextField(verbose_name='Titlul articolului')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Momentul crearii sursei')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Momentul ultimei modificari')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Numele spitalului')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.PositiveIntegerField(verbose_name='Numarul cazului')),
                ('collision_index', models.PositiveIntegerField(verbose_name='Indice suprapunere')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Momentul crearii cazului')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Momentul ultimei modificari')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Sex')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Varsta')),
                ('hospital_admission_date', models.DateField(blank=True, null=True, verbose_name='Data internarii')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='Data recoltarii probei')),
                ('positive_result_date', models.DateField(blank=True, null=True, verbose_name='Data rezultatului pozitiv')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Data decesului')),
                ('parsed_text', models.TextField(verbose_name='Textul interpretat')),
                ('validated', models.BooleanField(default=False, verbose_name='Deces validat manual')),
                ('comorbidities', models.ManyToManyField(blank=True, to='api_core.Comorbidity', verbose_name='Comorbiditati (conditii medicale existente)')),
                ('final_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finally_admitted_deaths', to='api_core.Hospital', verbose_name='Spitalul decesului')),
                ('initial_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initially_admitted_deaths', to='api_core.Hospital', verbose_name='Spitalul de internare initial')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_core.DataSource', verbose_name='Sursa de date')),
            ],
            options={
                'unique_together': {('case_number', 'collision_index')},
            },
        ),
    ]
