# Generated by Django 3.0.3 on 2020-04-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='url',
            field=models.URLField(unique=True, verbose_name='Sursa de informare'),
        ),
    ]
