# Generated by Django 3.0.3 on 2020-04-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0002_auto_20200420_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data decesului'),
        ),
        migrations.AlterField(
            model_name='death',
            name='final_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finally_admitted_deaths', to='api_core.Hospital', verbose_name='Spitalul decesului'),
        ),
        migrations.AlterField(
            model_name='death',
            name='hospital_admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data internarii'),
        ),
        migrations.AlterField(
            model_name='death',
            name='initial_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initially_admitted_deaths', to='api_core.Hospital', verbose_name='Spitalul de internare initial'),
        ),
        migrations.AlterField(
            model_name='death',
            name='positive_result_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data rezultatului pozitiv'),
        ),
        migrations.AlterField(
            model_name='death',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='Deces verificat manual'),
        ),
    ]
