# Generated by Django 3.0.3 on 2020-04-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api_core', '0003_merge_20200429_1347'), ('api_core', '0004_auto_20200429_1702'), ('api_core', '0005_statistics_search_string'), ('api_core', '0006_auto_20200429_1811')]

    dependencies = [
        ('api_core', '0002_statistics'),
        ('api_core', '0002_case_county'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Caz', 'verbose_name_plural': 'Cazuri'},
        ),
        migrations.AlterModelOptions(
            name='comorbidity',
            options={'verbose_name': 'Comorbiditate', 'verbose_name_plural': 'Comorbidități'},
        ),
        migrations.AlterModelOptions(
            name='datasource',
            options={'verbose_name': 'Sursă de date', 'verbose_name_plural': 'Surse de date'},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Spital', 'verbose_name_plural': 'Spitale'},
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name': 'Statistică', 'verbose_name_plural': 'Statistici'},
        ),
        migrations.AddField(
            model_name='statistics',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Momentul ultimei modificari'),
        ),
        migrations.AlterUniqueTogether(
            name='statistics',
            unique_together={('field', 'groups', 'filters', 'group_by_gender', 'group_by_county')},
        ),
        migrations.AddField(
            model_name='statistics',
            name='search_string',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='String de cautare'),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='Statistics',
            new_name='Statistic',
        ),
    ]
