# Generated by Django 3.0.3 on 2020-04-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0003_auto_20200420_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='title',
            field=models.TextField(default='', verbose_name='Titlul articolului'),
            preserve_default=False,
        ),
    ]
