# Generated by Django 3.0.3 on 2020-04-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0004_datasource_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='death',
            name='collision_index',
            field=models.PositiveIntegerField(default=1, verbose_name='Al catelea cu acelasi numar de caz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='death',
            name='case_number',
            field=models.PositiveIntegerField(verbose_name='Numarul cazului'),
        ),
        migrations.AlterUniqueTogether(
            name='death',
            unique_together={('case_number', 'collision_index')},
        ),
    ]
