# Generated by Django 3.0.3 on 2020-05-01 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api_core', '0004_fix_hunedoara_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_core.DataSource',
                                    verbose_name='Sursa de date'),
        ),
    ]
