# Generated by Django 3.0.3 on 2020-04-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0005_auto_20200420_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.PositiveIntegerField(verbose_name='Numarul cazului')),
                ('collision_index', models.PositiveIntegerField(verbose_name='Al catelea cu acelasi numar de caz (valabil doar cand apar coliziuni)')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Sex')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Varsta')),
                ('hospital_admission_date', models.DateField(blank=True, null=True, verbose_name='Data internarii')),
                ('positive_result_date', models.DateField(blank=True, null=True, verbose_name='Data rezultatului pozitiv')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Data decesului')),
                ('parsed_text', models.TextField(verbose_name='Textul interpretat')),
                ('validated', models.BooleanField(default=False, verbose_name='Deces verificat manual')),
                ('comorbidities', models.ManyToManyField(to='api_core.Comorbidity', verbose_name='Comorbiditati (conditii medicale existente)')),
                ('final_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finally_admitted_deaths', to='api_core.Hospital', verbose_name='Spitalul decesului')),
                ('initial_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initially_admitted_deaths', to='api_core.Hospital', verbose_name='Spitalul de internare initial')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_core.DataSource', verbose_name='Sursa de date')),
            ],
            options={
                'unique_together': {('case_number', 'collision_index')},
            },
        ),
        migrations.DeleteModel(
            name='Death',
        ),
    ]
